# Generated by Django 4.2.10 on 2024-06-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
